contentDir="topics"
baseURL = "/"
languageCode = "en"
title = "Maistra.io"
theme = "hugo-future-imperfect"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = false
ignorefiles=["DRAFTS/.*"]
# Disqus Username
disqusShortname = "disqus_shortname"

# Google Analytics UA number
googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Docs"
  weight = 1
  identifier = "docs"
  url = "/docs/"

[[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"

[[menu.main]]
  name = "Contribute"
  weight = 3
  identifier = "contribute"
  url = "/contribute/"

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/maistra"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/maistraio"
    name = "twitter"
    weight = 2

[params]
  accent = "#006264"
  backgroundColor = "#f5f5f5"
  highlightLanguages = ["r", "bash", "go", "yaml"]

  # Sets the meta tag description
  description          = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "Maistra"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/blog/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = true
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtTop       = true
  rssAppearAtBottom    = true
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = true
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # set to show or to hide categories in the sidebar
  showSidebarCategories = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = true
  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = false
  faviconVersion       = ""
  # Sets Social Share links to appear on posts
  socialShare          = true
  # Sets specific share to appear on posts (default behavior is to appear)
  socialShareTwitter   = true
  socialShareGoogleplus = true
  socialShareFacebook  = true
  socialShareReddit    = true
  socialShareLinkedin  = true
  socialShareStumbleupon = true
  socialSharePinterest = true
  socialShareEmail     = true

  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  # customCSS            = ["default", "/path/to/file"]
  # customJS             = ["default", "/path/to/file"]
  customCSS            = ["default"]
  customJS             = ["default"]

  # options for highlight.js (version, additional languages, and theme)
  disable_highlight = false # set to true to disable Highlight
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "css"]
  highlightjsTheme = "github"


# Disqus will take priority over Staticman (github.com/eduardoboucas/staticman)
# due to its ease of use. Feel free to check out both and decide what you would
# prefer to use. See Staticman.yml for additional settings.
[params.staticman]
  # Sets Statiman to be active
  staticman = false
  # Sets the location for Staticman to connect to
  username  = ""
  repo      = ""
  branch    = ""

  [params.staticman.recaptcha]
    sitekey = "SITE_KEY"
    secret  = "ENCRYPTED_SECRET"

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = "Hugo Future Imperfect"

  paragraph = "Another fine responsive site template by <a href=\"http://html5up.net\">HTML5 UP</a>. Ported by Julio Pescador with some extra goodies <i class='fa fa-hand-peace-o'></i>"

  about     = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "/img/main/logo.jpg"
    # Sets Image to be a cirlce
    circle    = false
    # Sets Image to be Future Imperfect's hexagon
    imperfect = true
    width     = ""
    alt       = "Hugo Future Imperfect"


